#### Householder Matrix

Orthogonal transformations

http://fourier.eng.hmc.edu/e176/lectures/NM/node10.html

In [1]:
import numpy as np

In [39]:
Vec = np.array([[1,5,9]])## any random vector, making it 2d
##make it a unit vector
uVec =Vec/np.linalg.norm(Vec)
uVec

array([[0.09667365, 0.48336824, 0.87006284]])

In [44]:
uVec@uVec.T

array([[1.]])

In [45]:
uVec.T@uVec

array([[0.00934579, 0.04672897, 0.08411215],
       [0.04672897, 0.23364486, 0.42056075],
       [0.08411215, 0.42056075, 0.75700935]])

#### Householder 1
H1 = I -2u*u.T

##### also a symmetric matrix

H1 = H1.Inv = H1.T

In [42]:
H1 = np.eye(uVec.shape[0]) -2 *uVec@uVec.T

#### Now H1 is a ortogonal matrix


In [43]:
np.dot(H1,H1.T)

array([[1.]])

In [28]:
H1

array([[ 0.96774194, -0.80645161, -1.16129032],
       [-0.03225806,  0.19354839, -1.16129032],
       [-0.03225806, -0.80645161, -0.16129032]])

##### we need to find u as per our vector x

#### Hadamard

In [46]:
Hd1 = np.array([[1,1],[1,-1]])
Hd1

array([[ 1,  1],
       [ 1, -1]])

In [48]:
np.concatenate((Hd1,Hd1))

array([[ 1,  1],
       [ 1, -1],
       [ 1,  1],
       [ 1, -1]])

In [49]:
np.concatenate((Hd1,-1*Hd1))

array([[ 1,  1],
       [ 1, -1],
       [-1, -1],
       [-1,  1]])

In [51]:
hd=np.concatenate((np.concatenate((Hd1,Hd1)),np.concatenate((Hd1,-1*Hd1))),axis=1)


array([[ 1,  1,  1,  1],
       [ 1, -1,  1, -1],
       [ 1,  1, -1, -1],
       [ 1, -1, -1,  1]])

In [52]:

hd@hd.T

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]])

In [ ]:
#### need to normalize

In [54]:
hd8 =np.concatenate((np.concatenate((hd,hd)),np.concatenate((hd,-1*hd))),axis=1)
hd8

array([[ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, -1,  1, -1,  1, -1,  1, -1],
       [ 1,  1, -1, -1,  1,  1, -1, -1],
       [ 1, -1, -1,  1,  1, -1, -1,  1],
       [ 1,  1,  1,  1, -1, -1, -1, -1],
       [ 1, -1,  1, -1, -1,  1, -1,  1],
       [ 1,  1, -1, -1, -1, -1,  1,  1],
       [ 1, -1, -1,  1, -1,  1,  1, -1]])

In [55]:
hd8@hd8.T

array([[8, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0, 0],
       [0, 0, 0, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

#### possible to get in multiples for 4, orthogonal matrics

In [60]:
##wavelets by Haar, another example
w4 = np.array([[1,1,1,1],[1,1,-1,-1],[1,-1,0,0],[0,0,1,-1]])
w4

array([[ 1,  1,  1,  1],
       [ 1,  1, -1, -1],
       [ 1, -1,  0,  0],
       [ 0,  0,  1, -1]])

In [61]:
w4@w4.T

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2]])

#### Discrete Fourier Transform

Eigen vectors of the following Q are 4 discret fourier transforms, to split vector into its frequencies

In [63]:
Q = np.array([[0,1,0,0],[0,0,1,0],[0,0,0,1],[1,0,0,0]])
Q

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])

In [64]:
Q@Q.T

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])